uncommented chages

diff --git a/.github/workflows/UI_CD_Workflow.yaml b/.github/workflows/UI_CD_Workflow.yaml
--- a/.github/workflows/UI_CD_Workflow.yaml
+++ b/.github/workflows/UI_CD_Workflow.yaml
@@ -91,8 +91,8 @@ jobs:
         if: ${{ github.event.inputs.test == 'true' }}
         run: |
           npm cache clean --force
-          # npm install
-          # npx prettier "**/*.{ts,css}" --check
+          npm install
+          npx prettier "**/*.{ts,css}" --check
 
       - name: Install Dependencies & Build UI
         run: |
@@ -137,92 +137,92 @@ jobs:
           docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
       
-  #     - name: Checkout Helm charts from Bitbucket
-  #       run: |
-  #         git clone ${{ secrets.SPEEDTOOLS_BITBUCKET_HELM_REPO }}
-  #         cd build-configurations/KnowHOW-Deploy/knowhow-ui
-  #         # Update values.yaml image tag
-  #         yq -i ".image.tag = \"${IMAGE_TAG}\"" $VALUES_FILE
-  #         git config user.name "github-actions"
-  #         git config user.email "github-actions@github.com"
-  #         git add $VALUES_FILE
-  #         git diff --cached --quiet || git commit -m "Update image tag to ${IMAGE_TAG}"
-  #         git push origin HEAD
+      - name: Checkout Helm charts from Bitbucket
+        run: |
+          git clone ${{ secrets.SPEEDTOOLS_BITBUCKET_HELM_REPO }}
+          cd build-configurations/KnowHOW-Deploy/knowhow-ui
+          # Update values.yaml image tag
+          yq -i ".image.tag = \"${IMAGE_TAG}\"" $VALUES_FILE
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+          git add $VALUES_FILE
+          git diff --cached --quiet || git commit -m "Update image tag to ${IMAGE_TAG}"
+          git push origin HEAD
 
-  # deploy:
-  #   runs-on: github-actions-self-hosted-runner
-  #   needs: build
-  #   env:
-  #     ARGOCD_APP_NAME: ${{ needs.build.outputs.argocd_app_name }}
-  #   steps:
-  #     - name: Install ArgoCD CLI
-  #       run: |
-  #         # Define a writable path within the runner's home directory
-  #         export ARGO_PATH="$HOME/bin"
-  #         mkdir -p $ARGO_PATH
+  deploy:
+    runs-on: github-actions-self-hosted-runner
+    needs: build
+    env:
+      ARGOCD_APP_NAME: ${{ needs.build.outputs.argocd_app_name }}
+    steps:
+      - name: Install ArgoCD CLI
+        run: |
+          # Define a writable path within the runner's home directory
+          export ARGO_PATH="$HOME/bin"
+          mkdir -p $ARGO_PATH
           
-  #         # Download ArgoCD CLI to the new path
-  #         curl -sSL -o "$ARGO_PATH/argocd" \
-  #           https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+          # Download ArgoCD CLI to the new path
+          curl -sSL -o "$ARGO_PATH/argocd" \
+            https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
           
-  #         # Make the downloaded file executable
-  #         chmod +x "$ARGO_PATH/argocd"
+          # Make the downloaded file executable
+          chmod +x "$ARGO_PATH/argocd"
           
-  #         # Add the new path to the shell's PATH
-  #         echo "$ARGO_PATH" >> $GITHUB_PATH
+          # Add the new path to the shell's PATH
+          echo "$ARGO_PATH" >> $GITHUB_PATH
 
-  #     - name: ArgoCD CLI Login
-  #       run: |
-  #         argocd login argocd-server \
-  #           --username ${{ secrets.SPEEDTOOLS_ARGOCD_USERNAME}} \
-  #           --password ${{ secrets.SPEEDTOOLS_ARGOCD_PASSWORD }} \
-  #           --plaintext
+      - name: ArgoCD CLI Login
+        run: |
+          argocd login argocd-server \
+            --username ${{ secrets.SPEEDTOOLS_ARGOCD_USERNAME}} \
+            --password ${{ secrets.SPEEDTOOLS_ARGOCD_PASSWORD }} \
+            --plaintext
       
-  #      # Step 2: Sync the application
-  #     - name: Sync application
-  #       id: sync-app
-  #       run: argocd app sync ${{ env.ARGOCD_APP_NAME }}
-  #       continue-on-error: true # Allow the workflow to proceed even if sync fails
+       # Step 2: Sync the application
+      - name: Sync application
+        id: sync-app
+        run: argocd app sync ${{ env.ARGOCD_APP_NAME }}
+        continue-on-error: true # Allow the workflow to proceed even if sync fails
         
-  #     # Step 3: Get application URL
-  #     - name: Get app URL for errors
-  #       id: get-url
-  #       if: ${{ steps.sync-app.outcome != 'success' }}
-  #       run: |
-  #         app_url=$(argocd app get ${{ env.ARGOCD_APP_NAME }} | grep 'URL:' | awk '{print $2}')
-  #         echo "APP_URL=${app_url}" >> $GITHUB_ENV
+      # Step 3: Get application URL
+      - name: Get app URL for errors
+        id: get-url
+        if: ${{ steps.sync-app.outcome != 'success' }}
+        run: |
+          app_url=$(argocd app get ${{ env.ARGOCD_APP_NAME }} | grep 'URL:' | awk '{print $2}')
+          echo "APP_URL=${app_url}" >> $GITHUB_ENV
         
-  #     # Step 4: Handle sync failure
-  #     - name: Handle Sync Failure
-  #       if: ${{ steps.sync-app.outcome != 'success' && env.APP_URL }}
-  #       run: |
-  #         echo "❌ Deployment failed: Sync for '${{ env.ARGOCD_APP_NAME }}' did not complete."
-  #         echo "View details here: ${{ env.APP_URL }}"
-  #         exit 1 # Fail the job
+      # Step 4: Handle sync failure
+      - name: Handle Sync Failure
+        if: ${{ steps.sync-app.outcome != 'success' && env.APP_URL }}
+        run: |
+          echo "❌ Deployment failed: Sync for '${{ env.ARGOCD_APP_NAME }}' did not complete."
+          echo "View details here: ${{ env.APP_URL }}"
+          exit 1 # Fail the job
       
-  #     # Step 5: Wait for the application to become healthy
-  #     - name: Wait for application health
-  #       id: wait-app
-  #       run: argocd app wait ${{ env.ARGOCD_APP_NAME }} --health --timeout 300
-  #       continue-on-error: true # Allow the workflow to proceed if the wait times out
+      # Step 5: Wait for the application to become healthy
+      - name: Wait for application health
+        id: wait-app
+        run: argocd app wait ${{ env.ARGOCD_APP_NAME }} --health --timeout 300
+        continue-on-error: true # Allow the workflow to proceed if the wait times out
 
-  #     # Step 6: Get application URL for wait failure
-  #     - name: Get app URL for wait failure
-  #       id: get-wait-url
-  #       if: ${{ steps.wait-app.outcome != 'success' }}
-  #       run: |
-  #         app_url=$(argocd app get ${{ env.ARGOCD_APP_NAME }} | grep 'URL:' | awk '{print $2}')
-  #         echo "APP_URL=${app_url}" >> $GITHUB_ENV
+      # Step 6: Get application URL for wait failure
+      - name: Get app URL for wait failure
+        id: get-wait-url
+        if: ${{ steps.wait-app.outcome != 'success' }}
+        run: |
+          app_url=$(argocd app get ${{ env.ARGOCD_APP_NAME }} | grep 'URL:' | awk '{print $2}')
+          echo "APP_URL=${app_url}" >> $GITHUB_ENV
 
-  #     # Step 7: Handle wait failure
-  #     - name: Handle Wait Failure
-  #       if: ${{ steps.wait-app.outcome != 'success' && env.APP_URL }}
-  #       run: |
-  #         echo "⚠️ '${{ env.ARGOCD_APP_NAME }}' is deployed but not healthy after timeout."
-  #         echo "Check app status and logs here: ${{ env.APP_URL }}"
-  #         exit 1 # Fail the job
+      # Step 7: Handle wait failure
+      - name: Handle Wait Failure
+        if: ${{ steps.wait-app.outcome != 'success' && env.APP_URL }}
+        run: |
+          echo "⚠️ '${{ env.ARGOCD_APP_NAME }}' is deployed but not healthy after timeout."
+          echo "Check app status and logs here: ${{ env.APP_URL }}"
+          exit 1 # Fail the job
       
-  #     - name: Deployment Succeeded
-  #       if: ${{ steps.sync-app.outcome == 'success' && steps.wait-app.outcome == 'success' }}
-  #       run: |
-  #         echo "✅ Deployment successful!"
+      - name: Deployment Succeeded
+        if: ${{ steps.sync-app.outcome == 'success' && steps.wait-app.outcome == 'success' }}
+        run: |
+          echo "✅ Deployment successful!"
